# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: marp install&build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 19

    ## https://qiita.com/flat35hd99/items/f981b0088a608d6d7974
    - uses: ConorMacBride/install-package@v1
      with:
        apt: fonts-noto
    - run: sudo npm install -g @marp-team/marp-cli
    - run: marp test.md --pptx  --allow-local-files
    - run: marp test.md --pdf   --allow-local-files
    - uses: actions/upload-artifact@v4
      with:
        name: pptx
        path: '*.pptx'
    - uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: '*.pdf'
